/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.JOptionPane;


/**
 *
 * @author 9spot
 */
public class EntornoGrafico extends javax.swing.JFrame {

    /**
     * Creates new form EntornoGrafico
     */
    public EntornoGrafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primernumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        segundonumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tercernumero = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        primernumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primernumero(evt);
            }
        });

        jLabel1.setText("Ingrese el primer numero");

        jLabel2.setText("Ingrese el segundo numero");

        segundonumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundonumero(evt);
            }
        });

        jLabel3.setText("Ingrese el segundo numero");

        tercernumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tercernumero(evt);
            }
        });

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(primernumero)
                        .addComponent(segundonumero)
                        .addComponent(tercernumero, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(primernumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(segundonumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tercernumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void primernumero(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primernumero
        // TODO add your handling code here:
    }//GEN-LAST:event_primernumero

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String numero1_text = primernumero.getText().trim();
    String numero2_text = segundonumero.getText().trim();
    String numero3_text = tercernumero.getText().trim();

    if (numero1_text.isEmpty() || numero2_text.isEmpty() || numero3_text.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingresa los tres números.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    double numero1, numero2, numero3;
    try {
        numero1 = Double.parseDouble(numero1_text);
        numero2 = Double.parseDouble(numero2_text);
        numero3 = Double.parseDouble(numero3_text);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Entrada inválida. Ingresa solo números (ej: 5 o 3.2).", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    StringBuilder sb = new StringBuilder();

    if (numero1 == numero2 && numero2 == numero3) {
        sb.append("Los tres números son iguales.\n");
    } else if (numero1 == numero2 && numero1 != numero3) {
        sb.append("El número 1 y el número 2 son iguales; el número 3 es distinto.\n");
    } else if (numero1 == numero3 && numero1 != numero2) {
        sb.append("El número 1 y el número 3 son iguales; el número 2 es distinto.\n");
    } else if (numero2 == numero3 && numero2 != numero1) {
        sb.append("El número 2 y el número 3 son iguales; el número 1 es distinto.\n");
    } else {
        sb.append("Los tres números son diferentes.\n");
    }

    double mayor = Math.max(numero1, Math.max(numero2, numero3));
    boolean m1 = (numero1 == mayor);
    boolean m2 = (numero2 == mayor);
    boolean m3 = (numero3 == mayor);

    if (m1 && !m2 && !m3) {
        sb.append(String.format("El mayor es el número 1 (%.2f).", numero1));
    } else if (!m1 && m2 && !m3) {
        sb.append(String.format("El mayor es el número 2 (%.2f).", numero2));
    } else if (!m1 && !m2 && m3) {
        sb.append(String.format("El mayor es el número 3 (%.2f).", numero3));
    } else {
        sb.append("Hay empate por el mayor entre: ");
        boolean primero = true;
        if (m1) { sb.append("número 1"); primero = false; }
        if (m2) { if (!primero) sb.append(", "); sb.append("número 2"); primero = false; }
        if (m3) { if (!primero) sb.append(", "); sb.append("número 3"); }
        sb.append(String.format(" (valor = %.2f).", mayor));
    }

    JOptionPane.showMessageDialog(this, sb.toString(), "Resultado", JOptionPane.INFORMATION_MESSAGE);
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tercernumero(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tercernumero
        // TODO add your handling code here:
    }//GEN-LAST:event_tercernumero

    private void segundonumero(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundonumero
        // TODO add your handling code here:
    }//GEN-LAST:event_segundonumero

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntornoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntornoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntornoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntornoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntornoGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField primernumero;
    private javax.swing.JTextField segundonumero;
    private javax.swing.JTextField tercernumero;
    // End of variables declaration//GEN-END:variables
}
